# Generated by Django 4.1.7 on 2023-05-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_options_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
